# Validate installation
- name: Validate installation
  command: "{{ virtualenvp }}/bin/python /opt/cito_plugin_server/manage.py validate"

- name: Modify cito-plugin-server.conf to run as root
  lineinfile:
    path: /opt/cito_plugin_server/bin/upstart/cito-plugin-server.conf
    regexp: 'exec /opt/cito_plugin_server/bin/cito-plugin-server.sh'
    line: 'exec sudo /opt/cito_plugin_server/bin/cito-plugin-server.sh'

- name: Configure services on startup
  command: "/opt/cito_plugin_server/bin/upstart/configure-upstart.sh"

# Start services
- name: Start CitoEngine Plugin Server
  shell: "nohup /opt/cito_plugin_server/bin/cito-plugin-server.sh </dev/null >/dev/null 2>&1 &"
