---
# Installing software-properties-common
- name: Installing software-properties-common
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - software-properties-common

# Installing ppa:ansible/ansible repository
- name: Installing ppa:ansible/ansible repository
  apt_repository:
    repo: "ppa:ansible/ansible"
    update_cache: yes

# Installing latest Ansible version
- name: Installing latest Ansible version
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - ansible
