# Downloading and installing the code
- name: Clone repo
  git:
    repo: https://github.com/CitoEngine/cito_engine
    dest: /tmp/cito_engine

- name: Run setup script
  command: python setup.py install
  args:
    chdir: /tmp/cito_engine

- name: Create virtualenv
  shell: "virtualenv {{ virtualenv }} && source {{ virtualenv }}/bin/activate"
  args:
    executable: /bin/bash

- name: Install requirements
  pip:
    requirements: /tmp/cito_engine/requirements.txt
    virtualenv: "{{ virtualenv }}"
